version: "3.9"
services:
  app:
    stdin_open: true
    build:
      context: .
    volumes:
      - ./:/redux
    ports:
      - "3000:3000"
    image: redux:react-dev
    container_name: redux_container
    command: yarn start
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true